[params]
    author = "Christian Mahnke"
    keywords = ""
    description = ""
    copyrightYears = "MMXXII - MMXXIII"
    cc = false
    stylesheets = []
    iiifCanvasHeight = 400
    iiifCanvasWidth = 300
    headerImage = "images/Logo.svg"
    disableScale = true
