[params]
    author = "Christian Mahnke"
    keywords = ""
    description = ""
    copyrightYears = "2023"
    cc = false
    stylesheets = []
    iiifCanvasHeight = 400
    iiifCanvasWidth = 300
    headerImage = "images/logo/logo.svg"
    disableScale = true
    favicon = "images/favicon-32.png"
