baseURL = "https://vintagereality.projektemacher.org/"
languageCode = "de"
title = 'Vintage Reality'
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
theme = ["projektemacher-base"]
paginate = 7

[languages]
  [languages.de]
    languagename = "Deutsch"

    [languages.de.params]

    [languages.de.menu]

      [[languages.de.menu.main]]
        name = "Start"
        URL = "/"
        weight = 1

      [[languages.de.menu.main]]
        name = "Karte"
        URL = "/map/"
        weight = 2

      [[languages.de.menu.main]]
        name = "Links"
        URL = "/links/"
        weight = 3

      [[languages.de.menu.main]]
        name = "Über"
        weight = 4
        url = "/about/"

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

[imaging]
    quality = 95

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
# See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

[outputFormats]

  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

[sitemap]
  changeFreq = 'weekly'

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

[build]
  writeStats = true
