baseURL = "https://vintagereality.projektemacher.org/"
languageCode = "de"
title = 'Vintage Reality'
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
theme = ["projektemacher-base"]
paginate = 5

[languages]
  [languages.de]
    languagename = "Deutsch"

    [languages.de.params]

    [languages.de.menu]

      [[languages.de.menu.main]]
        name = "Geplante Blogs"
        URL = "/future"
        weight = 1

      [[languages.de.menu.main]]
        name = "Über"
        weight = 5
        url = "about/"


[markup.goldmark.renderer]
  unsafe = true

[imaging]
    quality = 95

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
# See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

[outputFormats]

  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true
