baseURL = "https://vintagereality.projektemacher.org/"
languageCode = "de"
title = 'Vintage Reality'
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
theme = ["projektemacher-base"]
paginate = 5
